version: '3'
services:
  event-service:
    build: 
      context: src/
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "2000:1234"
    volumes:
      - ./config.yaml:/config.yaml
  postgres:
    image: postgres
    env_file:
      - .env-postgres
    expose:
      - 8000
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./postgres:/var/lib/postgresql/data 
  pgadmin:
    image: "dpage/pgadmin4"
    env_file:
      - .env-pgadmin 
    ports:
      - "2001:80"
    depends_on:
      - event-service


